// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CompaniesPublic
 */
export type CompaniesPublic = {
    /**
     * Data
     */
    data: Array<CompanyPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CompanyAdmin
 */
export type CompanyAdmin = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * CompanyAdmins
 */
export type CompanyAdmins = {
    /**
     * Data
     */
    data: Array<CompanyAdmin>;
};

/**
 * CompanyCreate
 */
export type CompanyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * CompanyPublic
 */
export type CompanyPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CompanyRole
 */
export type CompanyRole = 'member' | 'admin';

/**
 * CompanyUpdate
 */
export type CompanyUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: string;
    /**
     * Context
     */
    context?: {
        [key: string]: unknown;
    };
};

/**
 * JurisdictionAffectedQuery
 */
export type JurisdictionAffectedQuery = {
    /**
     * Jurisdiction Ids
     */
    jurisdiction_ids?: Array<string>;
    /**
     * Root Ids
     */
    root_ids?: Array<string>;
};

/**
 * JurisdictionAffectedUser
 */
export type JurisdictionAffectedUser = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Jurisdiction Count
     */
    jurisdiction_count: number;
};

/**
 * JurisdictionAffectedUsers
 */
export type JurisdictionAffectedUsers = {
    /**
     * Data
     */
    data: Array<JurisdictionAffectedUser>;
    /**
     * Count
     */
    count: number;
};

/**
 * JurisdictionCreate
 */
export type JurisdictionCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Structural
     */
    is_structural?: boolean;
    /**
     * Code
     */
    code?: string | null;
    region_type?: RegionType | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
};

/**
 * JurisdictionFacet
 */
export type JurisdictionFacet = {
    type: RegionType;
    /**
     * Label
     */
    label: string;
    /**
     * Options
     */
    options: Array<JurisdictionFacetOption>;
    /**
     * Value
     */
    value: Array<string>;
};

/**
 * JurisdictionFacetOption
 */
export type JurisdictionFacetOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Context
     */
    context?: string | null;
    /**
     * Flag Keys
     */
    flag_keys: Array<string>;
};

/**
 * JurisdictionFacets
 */
export type JurisdictionFacets = {
    /**
     * Facets
     */
    facets: Array<JurisdictionFacet>;
    /**
     * By Type
     */
    by_type: {
        [key in RegionType]?: Array<string>;
    };
    status_counts: JurisdictionStatusCounts;
    summary: JurisdictionSummary;
};

/**
 * JurisdictionFacetsQuery
 */
export type JurisdictionFacetsQuery = {
    /**
     * Scope
     */
    scope?: 'company' | 'user';
    filters?: JurisdictionFilters;
};

/**
 * JurisdictionFilters
 */
export type JurisdictionFilters = {
    /**
     * Search
     */
    search?: string;
    /**
     * By Type
     */
    by_type?: {
        [key in RegionType]?: Array<string>;
    };
    /**
     * Status
     */
    status?: 'all' | 'enabled' | 'available' | 'disabled';
};

/**
 * JurisdictionGridRow
 */
export type JurisdictionGridRow = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Structural
     */
    is_structural?: boolean;
    /**
     * Code
     */
    code?: string | null;
    region_type?: RegionType | null;
    /**
     * Id
     */
    id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Depth
     */
    depth: number;
    /**
     * Path
     */
    path: string;
    /**
     * Name Path
     */
    name_path: string;
    /**
     * Child Count
     */
    child_count?: number;
    /**
     * Display Depth
     */
    display_depth: number;
    /**
     * Has Children
     */
    has_children: boolean;
    /**
     * Expanded
     */
    expanded: boolean;
    /**
     * Is Match
     */
    is_match: boolean;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Licensed
     */
    licensed: boolean;
    /**
     * Locked
     */
    locked: boolean;
    /**
     * Flag Keys
     */
    flag_keys: Array<string>;
    subtree?: SubtreeSelection | null;
    /**
     * User Count
     */
    user_count?: number | null;
};

/**
 * JurisdictionIds
 */
export type JurisdictionIds = {
    /**
     * Jurisdiction Ids
     */
    jurisdiction_ids: Array<string>;
    /**
     * Count
     */
    count: number;
};

/**
 * JurisdictionPublic
 */
export type JurisdictionPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Structural
     */
    is_structural?: boolean;
    /**
     * Code
     */
    code?: string | null;
    region_type?: RegionType | null;
    /**
     * Id
     */
    id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Depth
     */
    depth: number;
    /**
     * Path
     */
    path: string;
    /**
     * Name Path
     */
    name_path: string;
    /**
     * Child Count
     */
    child_count?: number;
};

/**
 * JurisdictionRowsPage
 */
export type JurisdictionRowsPage = {
    /**
     * Data
     */
    data: Array<JurisdictionGridRow>;
    /**
     * Total
     */
    total: number;
    /**
     * Start
     */
    start: number;
    /**
     * Expanded Ids
     */
    expanded_ids: Array<string>;
};

/**
 * JurisdictionRowsQuery
 */
export type JurisdictionRowsQuery = {
    /**
     * Scope
     */
    scope?: 'company' | 'user';
    filters?: JurisdictionFilters;
    /**
     * Sort By
     */
    sort_by?: 'name' | 'enabled' | null;
    /**
     * Sort Dir
     */
    sort_dir?: 'asc' | 'desc';
    /**
     * Expanded Ids
     */
    expanded_ids?: Array<string> | null;
    /**
     * Expand All
     */
    expand_all?: boolean;
    /**
     * Start
     */
    start?: number;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * JurisdictionSelection
 */
export type JurisdictionSelection = {
    /**
     * Jurisdiction Ids
     */
    jurisdiction_ids: Array<string>;
};

/**
 * JurisdictionStatusCounts
 */
export type JurisdictionStatusCounts = {
    /**
     * All
     */
    all: number;
    /**
     * Enabled
     */
    enabled: number;
    /**
     * Available
     */
    available: number;
    /**
     * Disabled
     */
    disabled: number;
};

/**
 * JurisdictionSubtreeToggle
 */
export type JurisdictionSubtreeToggle = {
    /**
     * Root Id
     */
    root_id: string;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * JurisdictionSummary
 */
export type JurisdictionSummary = {
    /**
     * Total
     */
    total: number;
    /**
     * Shown
     */
    shown: number;
    /**
     * Enabled
     */
    enabled: number;
    /**
     * Locked
     */
    locked?: number | null;
};

/**
 * JurisdictionUpdate
 */
export type JurisdictionUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Is Structural
     */
    is_structural?: boolean | null;
    /**
     * Code
     */
    code?: string | null;
    region_type?: RegionType | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
};

/**
 * JurisdictionUserCount
 */
export type JurisdictionUserCount = {
    /**
     * Jurisdiction Id
     */
    jurisdiction_id: string;
    /**
     * User Count
     */
    user_count: number;
};

/**
 * JurisdictionUserCounts
 */
export type JurisdictionUserCounts = {
    /**
     * Data
     */
    data: Array<JurisdictionUserCount>;
};

/**
 * JurisdictionsPublic
 */
export type JurisdictionsPublic = {
    /**
     * Data
     */
    data: Array<JurisdictionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
    /**
     * Company Id
     */
    company_id?: string | null;
    company_role?: CompanyRole;
};

/**
 * RegionType
 */
export type RegionType = 'country' | 'subdivision' | 'city';

/**
 * SubtreeSelection
 */
export type SubtreeSelection = {
    /**
     * Total
     */
    total: number;
    /**
     * Enabled
     */
    enabled: number;
    /**
     * Locked
     */
    locked: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
    /**
     * Company Id
     */
    company_id?: string | null;
    company_role?: CompanyRole;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Company Id
     */
    company_id: string;
    company_role: CompanyRole;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Company Id
     */
    company_id?: string | null;
    company_role?: CompanyRole | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/logout';
};

export type loginLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type loginLogoutError = loginLogoutErrors[keyof loginLogoutErrors];

export type loginLogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginLogoutResponse = loginLogoutResponses[keyof loginLogoutResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type loginTestTokenError = loginTestTokenErrors[keyof loginTestTokenErrors];

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersDeleteUserMeError = usersDeleteUserMeErrors[keyof usersDeleteUserMeErrors];

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadUserMeError = usersReadUserMeErrors[keyof usersReadUserMeErrors];

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersReadMyJurisdictionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/jurisdictions';
};

export type usersReadMyJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadMyJurisdictionsError = usersReadMyJurisdictionsErrors[keyof usersReadMyJurisdictionsErrors];

export type usersReadMyJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type usersReadMyJurisdictionsResponse = usersReadMyJurisdictionsResponses[keyof usersReadMyJurisdictionsResponses];

export type usersSetMyJurisdictionsData = {
    body: JurisdictionSelection;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/jurisdictions';
};

export type usersSetMyJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersSetMyJurisdictionsError = usersSetMyJurisdictionsErrors[keyof usersSetMyJurisdictionsErrors];

export type usersSetMyJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type usersSetMyJurisdictionsResponse = usersSetMyJurisdictionsResponses[keyof usersSetMyJurisdictionsResponses];

export type usersReadMyJurisdictionIdsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/jurisdictions/ids';
};

export type usersReadMyJurisdictionIdsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadMyJurisdictionIdsError = usersReadMyJurisdictionIdsErrors[keyof usersReadMyJurisdictionIdsErrors];

export type usersReadMyJurisdictionIdsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionIds;
};

export type usersReadMyJurisdictionIdsResponse = usersReadMyJurisdictionIdsResponses[keyof usersReadMyJurisdictionIdsResponses];

export type usersToggleMyJurisdictionSubtreeData = {
    body: JurisdictionSubtreeToggle;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/jurisdictions/subtree';
};

export type usersToggleMyJurisdictionSubtreeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersToggleMyJurisdictionSubtreeError = usersToggleMyJurisdictionSubtreeErrors[keyof usersToggleMyJurisdictionSubtreeErrors];

export type usersToggleMyJurisdictionSubtreeResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionIds;
};

export type usersToggleMyJurisdictionSubtreeResponse = usersToggleMyJurisdictionSubtreeResponses[keyof usersToggleMyJurisdictionSubtreeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type usersReadUserJurisdictionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/jurisdictions';
};

export type usersReadUserJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadUserJurisdictionsError = usersReadUserJurisdictionsErrors[keyof usersReadUserJurisdictionsErrors];

export type usersReadUserJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type usersReadUserJurisdictionsResponse = usersReadUserJurisdictionsResponses[keyof usersReadUserJurisdictionsResponses];

export type usersSetUserJurisdictionsData = {
    body: JurisdictionSelection;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/jurisdictions';
};

export type usersSetUserJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersSetUserJurisdictionsError = usersSetUserJurisdictionsErrors[keyof usersSetUserJurisdictionsErrors];

export type usersSetUserJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type usersSetUserJurisdictionsResponse = usersSetUserJurisdictionsResponses[keyof usersSetUserJurisdictionsResponses];

export type usersReadUserJurisdictionIdsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/jurisdictions/ids';
};

export type usersReadUserJurisdictionIdsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type usersReadUserJurisdictionIdsError = usersReadUserJurisdictionIdsErrors[keyof usersReadUserJurisdictionIdsErrors];

export type usersReadUserJurisdictionIdsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionIds;
};

export type usersReadUserJurisdictionIdsResponse = usersReadUserJurisdictionIdsResponses[keyof usersReadUserJurisdictionIdsResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type jurisdictionsReadJurisdictionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Parent Id
         */
        parent_id?: string | null;
    };
    url: '/api/v1/jurisdictions/';
};

export type jurisdictionsReadJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsReadJurisdictionsError = jurisdictionsReadJurisdictionsErrors[keyof jurisdictionsReadJurisdictionsErrors];

export type jurisdictionsReadJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type jurisdictionsReadJurisdictionsResponse = jurisdictionsReadJurisdictionsResponses[keyof jurisdictionsReadJurisdictionsResponses];

export type jurisdictionsCreateJurisdictionData = {
    body: JurisdictionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/jurisdictions/';
};

export type jurisdictionsCreateJurisdictionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsCreateJurisdictionError = jurisdictionsCreateJurisdictionErrors[keyof jurisdictionsCreateJurisdictionErrors];

export type jurisdictionsCreateJurisdictionResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionPublic;
};

export type jurisdictionsCreateJurisdictionResponse = jurisdictionsCreateJurisdictionResponses[keyof jurisdictionsCreateJurisdictionResponses];

export type jurisdictionsReadJurisdictionTreeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sort By
         */
        sort_by?: 'name' | 'enabled' | null;
        /**
         * Sort Dir
         */
        sort_dir?: 'asc' | 'desc';
        /**
         * Scope
         */
        scope?: 'company' | 'user';
    };
    url: '/api/v1/jurisdictions/tree';
};

export type jurisdictionsReadJurisdictionTreeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsReadJurisdictionTreeError = jurisdictionsReadJurisdictionTreeErrors[keyof jurisdictionsReadJurisdictionTreeErrors];

export type jurisdictionsReadJurisdictionTreeResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type jurisdictionsReadJurisdictionTreeResponse = jurisdictionsReadJurisdictionTreeResponses[keyof jurisdictionsReadJurisdictionTreeResponses];

export type jurisdictionsReadJurisdictionRowsData = {
    body: JurisdictionRowsQuery;
    path?: never;
    query?: never;
    url: '/api/v1/jurisdictions/rows';
};

export type jurisdictionsReadJurisdictionRowsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsReadJurisdictionRowsError = jurisdictionsReadJurisdictionRowsErrors[keyof jurisdictionsReadJurisdictionRowsErrors];

export type jurisdictionsReadJurisdictionRowsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionRowsPage;
};

export type jurisdictionsReadJurisdictionRowsResponse = jurisdictionsReadJurisdictionRowsResponses[keyof jurisdictionsReadJurisdictionRowsResponses];

export type jurisdictionsReadJurisdictionFacetsData = {
    body: JurisdictionFacetsQuery;
    path?: never;
    query?: never;
    url: '/api/v1/jurisdictions/facets';
};

export type jurisdictionsReadJurisdictionFacetsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsReadJurisdictionFacetsError = jurisdictionsReadJurisdictionFacetsErrors[keyof jurisdictionsReadJurisdictionFacetsErrors];

export type jurisdictionsReadJurisdictionFacetsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionFacets;
};

export type jurisdictionsReadJurisdictionFacetsResponse = jurisdictionsReadJurisdictionFacetsResponses[keyof jurisdictionsReadJurisdictionFacetsResponses];

export type jurisdictionsDeleteJurisdictionData = {
    body?: never;
    path: {
        /**
         * Jurisdiction Id
         */
        jurisdiction_id: string;
    };
    query?: never;
    url: '/api/v1/jurisdictions/{jurisdiction_id}';
};

export type jurisdictionsDeleteJurisdictionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsDeleteJurisdictionError = jurisdictionsDeleteJurisdictionErrors[keyof jurisdictionsDeleteJurisdictionErrors];

export type jurisdictionsDeleteJurisdictionResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type jurisdictionsDeleteJurisdictionResponse = jurisdictionsDeleteJurisdictionResponses[keyof jurisdictionsDeleteJurisdictionResponses];

export type jurisdictionsReadJurisdictionData = {
    body?: never;
    path: {
        /**
         * Jurisdiction Id
         */
        jurisdiction_id: string;
    };
    query?: never;
    url: '/api/v1/jurisdictions/{jurisdiction_id}';
};

export type jurisdictionsReadJurisdictionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsReadJurisdictionError = jurisdictionsReadJurisdictionErrors[keyof jurisdictionsReadJurisdictionErrors];

export type jurisdictionsReadJurisdictionResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionPublic;
};

export type jurisdictionsReadJurisdictionResponse = jurisdictionsReadJurisdictionResponses[keyof jurisdictionsReadJurisdictionResponses];

export type jurisdictionsUpdateJurisdictionData = {
    body: JurisdictionUpdate;
    path: {
        /**
         * Jurisdiction Id
         */
        jurisdiction_id: string;
    };
    query?: never;
    url: '/api/v1/jurisdictions/{jurisdiction_id}';
};

export type jurisdictionsUpdateJurisdictionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type jurisdictionsUpdateJurisdictionError = jurisdictionsUpdateJurisdictionErrors[keyof jurisdictionsUpdateJurisdictionErrors];

export type jurisdictionsUpdateJurisdictionResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionPublic;
};

export type jurisdictionsUpdateJurisdictionResponse = jurisdictionsUpdateJurisdictionResponses[keyof jurisdictionsUpdateJurisdictionResponses];

export type companiesReadCompaniesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/companies/';
};

export type companiesReadCompaniesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompaniesError = companiesReadCompaniesErrors[keyof companiesReadCompaniesErrors];

export type companiesReadCompaniesResponses = {
    /**
     * Successful Response
     */
    200: CompaniesPublic;
};

export type companiesReadCompaniesResponse = companiesReadCompaniesResponses[keyof companiesReadCompaniesResponses];

export type companiesCreateCompanyData = {
    body: CompanyCreate;
    path?: never;
    query?: never;
    url: '/api/v1/companies/';
};

export type companiesCreateCompanyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesCreateCompanyError = companiesCreateCompanyErrors[keyof companiesCreateCompanyErrors];

export type companiesCreateCompanyResponses = {
    /**
     * Successful Response
     */
    200: CompanyPublic;
};

export type companiesCreateCompanyResponse = companiesCreateCompanyResponses[keyof companiesCreateCompanyResponses];

export type companiesReadCompanyData = {
    body?: never;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}';
};

export type companiesReadCompanyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompanyError = companiesReadCompanyErrors[keyof companiesReadCompanyErrors];

export type companiesReadCompanyResponses = {
    /**
     * Successful Response
     */
    200: CompanyPublic;
};

export type companiesReadCompanyResponse = companiesReadCompanyResponses[keyof companiesReadCompanyResponses];

export type companiesUpdateCompanyData = {
    body: CompanyUpdate;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}';
};

export type companiesUpdateCompanyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesUpdateCompanyError = companiesUpdateCompanyErrors[keyof companiesUpdateCompanyErrors];

export type companiesUpdateCompanyResponses = {
    /**
     * Successful Response
     */
    200: CompanyPublic;
};

export type companiesUpdateCompanyResponse = companiesUpdateCompanyResponses[keyof companiesUpdateCompanyResponses];

export type companiesReadCompanyAdminsData = {
    body?: never;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/admins';
};

export type companiesReadCompanyAdminsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompanyAdminsError = companiesReadCompanyAdminsErrors[keyof companiesReadCompanyAdminsErrors];

export type companiesReadCompanyAdminsResponses = {
    /**
     * Successful Response
     */
    200: CompanyAdmins;
};

export type companiesReadCompanyAdminsResponse = companiesReadCompanyAdminsResponses[keyof companiesReadCompanyAdminsResponses];

export type companiesReadCompanyJurisdictionsData = {
    body?: never;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/jurisdictions';
};

export type companiesReadCompanyJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompanyJurisdictionsError = companiesReadCompanyJurisdictionsErrors[keyof companiesReadCompanyJurisdictionsErrors];

export type companiesReadCompanyJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type companiesReadCompanyJurisdictionsResponse = companiesReadCompanyJurisdictionsResponses[keyof companiesReadCompanyJurisdictionsResponses];

export type companiesSetCompanyJurisdictionsData = {
    body: JurisdictionSelection;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/jurisdictions';
};

export type companiesSetCompanyJurisdictionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesSetCompanyJurisdictionsError = companiesSetCompanyJurisdictionsErrors[keyof companiesSetCompanyJurisdictionsErrors];

export type companiesSetCompanyJurisdictionsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionsPublic;
};

export type companiesSetCompanyJurisdictionsResponse = companiesSetCompanyJurisdictionsResponses[keyof companiesSetCompanyJurisdictionsResponses];

export type companiesReadCompanyJurisdictionIdsData = {
    body?: never;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/jurisdictions/ids';
};

export type companiesReadCompanyJurisdictionIdsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompanyJurisdictionIdsError = companiesReadCompanyJurisdictionIdsErrors[keyof companiesReadCompanyJurisdictionIdsErrors];

export type companiesReadCompanyJurisdictionIdsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionIds;
};

export type companiesReadCompanyJurisdictionIdsResponse = companiesReadCompanyJurisdictionIdsResponses[keyof companiesReadCompanyJurisdictionIdsResponses];

export type companiesToggleCompanyJurisdictionSubtreeData = {
    body: JurisdictionSubtreeToggle;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/jurisdictions/subtree';
};

export type companiesToggleCompanyJurisdictionSubtreeErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesToggleCompanyJurisdictionSubtreeError = companiesToggleCompanyJurisdictionSubtreeErrors[keyof companiesToggleCompanyJurisdictionSubtreeErrors];

export type companiesToggleCompanyJurisdictionSubtreeResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionIds;
};

export type companiesToggleCompanyJurisdictionSubtreeResponse = companiesToggleCompanyJurisdictionSubtreeResponses[keyof companiesToggleCompanyJurisdictionSubtreeResponses];

export type companiesReadCompanyJurisdictionUserCountsData = {
    body?: never;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/jurisdictions/user-counts';
};

export type companiesReadCompanyJurisdictionUserCountsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompanyJurisdictionUserCountsError = companiesReadCompanyJurisdictionUserCountsErrors[keyof companiesReadCompanyJurisdictionUserCountsErrors];

export type companiesReadCompanyJurisdictionUserCountsResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionUserCounts;
};

export type companiesReadCompanyJurisdictionUserCountsResponse = companiesReadCompanyJurisdictionUserCountsResponses[keyof companiesReadCompanyJurisdictionUserCountsResponses];

export type companiesReadCompanyJurisdictionAffectedUsersData = {
    body: JurisdictionAffectedQuery;
    path: {
        /**
         * Company Id
         */
        company_id: string;
    };
    query?: never;
    url: '/api/v1/companies/{company_id}/jurisdictions/affected-users';
};

export type companiesReadCompanyJurisdictionAffectedUsersErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type companiesReadCompanyJurisdictionAffectedUsersError = companiesReadCompanyJurisdictionAffectedUsersErrors[keyof companiesReadCompanyJurisdictionAffectedUsersErrors];

export type companiesReadCompanyJurisdictionAffectedUsersResponses = {
    /**
     * Successful Response
     */
    200: JurisdictionAffectedUsers;
};

export type companiesReadCompanyJurisdictionAffectedUsersResponse = companiesReadCompanyJurisdictionAffectedUsersResponses[keyof companiesReadCompanyJurisdictionAffectedUsersResponses];

export type serviceReadUserJurisdictionIdsForServiceData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/service/users/{user_id}/jurisdiction-ids';
};

export type serviceReadUserJurisdictionIdsForServiceErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type serviceReadUserJurisdictionIdsForServiceError = serviceReadUserJurisdictionIdsForServiceErrors[keyof serviceReadUserJurisdictionIdsForServiceErrors];

export type serviceReadUserJurisdictionIdsForServiceResponses = {
    /**
     * Response Service-Read User Jurisdiction Ids For Service
     *
     * Successful Response
     */
    200: Array<string>;
};

export type serviceReadUserJurisdictionIdsForServiceResponse = serviceReadUserJurisdictionIdsForServiceResponses[keyof serviceReadUserJurisdictionIdsForServiceResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Conflict
     */
    409: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: ErrorResponse;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
