"""add revoked token

Revision ID: 6f40065b7e91
Revises: b4520842759f
Create Date: 2026-10-07 13:18:17.577225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f40065b7e91'
down_revision = 'b4520842759f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revokedtoken',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revokedtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revokedtoken_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revokedtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revokedtoken_expires_at'))

    op.drop_table('revokedtoken')
    # ### end Alembic commands ###
