"""add jurisdiction

Revision ID: b4520842759f
Revises: 2744a5e2271f
Create Date: 2026-10-07 12:38:17.591196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4520842759f'
down_revision = '2744a5e2271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_structural', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('name_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.CheckConstraint('depth >= 0', name='ck_jurisdiction_depth'),
    sa.CheckConstraint('sort_order >= 0', name='ck_jurisdiction_sort_order'),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdiction.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_jurisdiction_parent_name')
    )
    with op.batch_alter_table('jurisdiction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jurisdiction_name'), ['name'], unique=False)
        batch_op.create_index('ix_jurisdiction_parent_sort', ['parent_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_path'), ['path'], unique=True)
        batch_op.create_index('ix_jurisdiction_root_name', ['name'], unique=True, sqlite_where=sa.text('parent_id IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jurisdiction', schema=None) as batch_op:
        batch_op.drop_index('ix_jurisdiction_root_name', sqlite_where=sa.text('parent_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_path'))
        batch_op.drop_index('ix_jurisdiction_parent_sort')
        batch_op.drop_index(batch_op.f('ix_jurisdiction_name'))

    op.drop_table('jurisdiction')
    # ### end Alembic commands ###
