/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recoverPassword'
import { Route as ResetPasswordRouteImport } from './routes/resetPassword'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCompanyAdminRouteImport } from './routes/_layout/companyAdmin'
import { Route as LayoutJurisdictionsRouteImport } from './routes/_layout/jurisdictions'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recoverPassword',
  path: '/recoverPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompanyAdminRoute = LayoutCompanyAdminRouteImport.update({
  id: '/companyAdmin',
  path: '/companyAdmin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJurisdictionsRoute = LayoutJurisdictionsRouteImport.update({
  id: '/jurisdictions',
  path: '/jurisdictions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recoverPassword': typeof RecoverPasswordRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/companyAdmin': typeof LayoutCompanyAdminRoute
  '/jurisdictions': typeof LayoutJurisdictionsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recoverPassword': typeof RecoverPasswordRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/companyAdmin': typeof LayoutCompanyAdminRoute
  '/jurisdictions': typeof LayoutJurisdictionsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recoverPassword': typeof RecoverPasswordRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/companyAdmin': typeof LayoutCompanyAdminRoute
  '/_layout/jurisdictions': typeof LayoutJurisdictionsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recoverPassword'
    | '/resetPassword'
    | '/signup'
    | '/admin'
    | '/companyAdmin'
    | '/jurisdictions'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recoverPassword'
    | '/resetPassword'
    | '/signup'
    | '/admin'
    | '/companyAdmin'
    | '/jurisdictions'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recoverPassword'
    | '/resetPassword'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/companyAdmin'
    | '/_layout/jurisdictions'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recoverPassword': {
      id: '/recoverPassword'
      path: '/recoverPassword'
      fullPath: '/recoverPassword'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/companyAdmin': {
      id: '/_layout/companyAdmin'
      path: '/companyAdmin'
      fullPath: '/companyAdmin'
      preLoaderRoute: typeof LayoutCompanyAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jurisdictions': {
      id: '/_layout/jurisdictions'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof LayoutJurisdictionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCompanyAdminRoute: typeof LayoutCompanyAdminRoute
  LayoutJurisdictionsRoute: typeof LayoutJurisdictionsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCompanyAdminRoute: LayoutCompanyAdminRoute,
  LayoutJurisdictionsRoute: LayoutJurisdictionsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
